{{- if and .Values.serviceAccount.create .Values.rbac.enable }}
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: jgroups-kubeping-pod-reader-{{ .Release.Namespace }}
  labels:
    {{- include "keycloak.labels" . | nindent 4 }}
{{- with .Values.rbac.rules }}
rules:
  {{- toYaml . | nindent 4 }}
{{- end }}
{{- end}}