{{- if .Values.podDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := .Values.podDisruptionBudgetAnnotations }}
    {{ printf "%s: %s" $key ($val | quote) | nindent 4 }}
    {{- end }}
  labels:
    {{- range $key, $val := .Values.podDisruptionBudgetLabels }}
    {{ printf "%s: %s" $key ($val | quote) | nindent 4 }}
    {{- end }}
    {{- include "keycloak.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "keycloak.selectorLabels" . | nindent 6 }}
  {{- toYaml .Values.podDisruptionBudget | nindent 2}}
{{- end }}