apiVersion: v1
kind: Service
metadata:
  name: {{ include "keycloak.fullname" . }}-http
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{- printf "%s: %s" $key ($val | quote) | nindent 4 }}
    {{- end }}
  labels:
    {{- range $key, $val := .Values.service.labels }}
    {{ printf "%s: %s" $key ($val | quote) | nindent 4 }}
    {{- end }}
    {{- include "keycloak.labels" . | nindent 4 }}
    app.kubernetes.io/component: http
spec:
  type: ClusterIP
  {{- if and (eq "LoadBalancer" .Values.service.type) .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq "LoadBalancer" .Values.service.type) .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if eq "LoadBalancer" .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
    {{- with .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}

  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      {{- if and (or (eq "NodePort" .Values.service.type) (eq "LoadBalancer" .Values.service.type)) .Values.service.httpNodePort }}
      nodePort: {{ .Values.service.httpNodePort }}
      {{- end }}
      protocol: TCP
      name: http
    {{- if .Values.service.httpsPort }}
    - port: {{ .Values.service.httpsPort }}
      targetPort: https
      {{- if and (or (eq "NodePort" .Values.service.type) (eq "LoadBalancer" .Values.service.type)) .Values.service.httpsNodePort }}
      nodePort: {{ .Values.service.httpsNodePort }}
      {{- end }}
      protocol: TCP
      name: https
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector:
    {{- include "keycloak.selectorLabels" . | nindent 4 }}